Project Tabi {
  database_type: 'PostgreSQL'
  Note: '''
    # ChainCohort Database
    **markdown content here**
  '''
}

Table user as u {
    id int [pk, increment]
    email text
    wallet_address text
    first_name text
    last_name text
    is_student boolean
    username text
    telegram text
    facebook text
    twitter text
    discord text
}

Table mission_category as mc {
  id int [pk, increment]
  name text
  description text
}

Table mission as m {
    id int [pk, increment]
    title text
    description text
    start_date text
    end_date text
    banner text
    mission_category_id int [ref: > mc.id]
}

Table task as t {
    id int [pk, increment]
    mission_id int [ref: > m.id]
    type text
    name text
    description text
    action text
    xp int
    button_placeholder text
}

Table completed_task as ct {
    id int [pk, increment]
    user_id int [ref: > u.id]
    task_id int [ref: > t.id]
    completed_date date
}

Table proofs_of_work as p {
    id int [pk, increment]
    user_id int [ref: > u.id]
    task_id int [ref: > t.id]
    link text
    image text
}

Table reward as r {
    id int [pk, increment]
    name text
    description text
    type text
    quantity int
    image text
    requirement text
}